### PR TITLE
Snapshot builds & Java 8 update site compatibility

### PR DESCRIPTION
**Pull request by skalarproduktraum**
Heya!

This PR enables SNAPSHOT builds in pom.xml, making it easy to build a version of the plugin against a locally created ClearVolume package. The default build profile will be the SNAPSHOT configuration, while a production build can be made by `mvn -Pproduction`. Do @fjug or @tpietzsch have some feedback on whether this mechanism is good or should be scrapped?

### CODE REVIEW

**Comment by fjug** [comment]
Sounds good to me… not an expert though…

**Comment by skalarproduktraum** [comment]
I forgot describing the basic workflow:

1. you make awesome changes in the ClearVolume world, then you run `gradle install` there which installs a SNAPSHOT build of ClearVolume/GL/CUDA in the local Maven repo.
2. you run `mvn` in the imglib2-clearvolume directory
3. you get a shiny imglib2 plugin with your current changes that you can also easily transfer to other machines for testing.
4. profit

**Comment by fjug** [comment]
Yes, that sounds 100% sweet!

**Comment by tpietzsch** [comment]
Hi,

maybe have a look at this:
http://fiji.sc/Architecture#Using_snapshot_couplings_during_development

This is the “IJ2 way” of doing it.
Basically, if you want SNAPSHOT couplings temporarily, you just put a (empty) "dev token" files:
~/.scijava/dev.imagej
~/.scijava/dev.imglib2
etc. and this is picked up by the pom somehow and it switches to SNAPSHOT couplings.
I’m not familiar with the details however...

best regards,
Tobias

**Comment by royerloic** [comment]
great work Ulrik!

**Comment by fjug** [comment]
That sounds interesting… if any of us ever understand some of the details… I would be happy to hear about it then… ;)

**Comment by skalarproduktraum** [comment]
Thanks @tpietzsch! 

At the moment, I'd prefer the command line switch way, as it seems more portable and easier to achieve with both build systems:
* where would the dotfiles go on Windows? `C:\Users\myuser\.clearvolume`?
* I don't know if Maven can check for the existence of a file during the build and set flags accordingly. The switch way is easy with both Gradle and Maven

**Comment by tpietzsch** [comment]
On 26 Oct 2015, at 21:11, Ulrik Guenther <notifications@github.com> wrote:

> Thanks @tpietzsch!
> 
> At the moment, I'd prefer the command line switch way, as it seems more portable and easier to achieve with both build systems:
> 
Sure, I understand that.
> where would the dotfiles go on Windows? C:\Users\myuser\.clearvolume?
No idea.
> I don't know if Maven can check for the existence of a file during the build and set flags accordingly.
Obviously, yes :-)



But I agree, let’s do it your way for now. At the hackathon, we can ask Curtis to explain how the IJ2 dev-profiles work, then we can switch if it’s useful...


best regards,
Tobias

**Comment by skalarproduktraum** [comment]
This branch also removes the maven-shade plugin now, which makes the plugin compatible with the Java 8 update site in Fiji.

**Pull request merged**
