### PR TITLE
Load Optimizations & Profiling (WIP)

### PR DESCRIPTION
**Pull request by skalarproduktraum**
Thanks to @tpietzsch, the ImgLib2 plugin now loads images much fast, as cursors are handled better.

This also got us curious about the overall transfer performance, so this pull request adds time profiling for RAM -> GPU transfer and ImgLib2 conversion.

If you want to run the plugin with profiling enabled, e.g. run Fiji by `/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx -DClearVolume.EnableProfiling=1`

### CODE REVIEW

**Comment by ctrueden** [comment]
@fjug Did you notice this? It looks really nice...

**Comment by fjug** [comment]
Awesome, thanks @ctrueden for pointing me what was done one floor below me... ;)

**Comment by skalarproduktraum** [comment]
@fjug: This was actually started when we were still on the same floor 😛 

Here are some statistics:
screen shot 2017-04-10 at 10 54 08

The CoreMem part needs some freeing code (which I can probably do in the next days), then we could merge this if you like.

**Comment by fjug** [comment]
Thanks guys... sorry for the long wait...

**Pull request merged**
